name: public_parking_info_fe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  kakao_map_plugin: ^0.3.6
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  dio: ^5.8.0+1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  flutter_dotenv: ^5.2.1
  riverpod: ^2.6.1
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  go_router: ^15.1.1
  sidebarx: ^0.17.1
  spider: ^4.2.2
  smooth_page_indicator: ^1.2.1
  dropdown_button2: ^2.3.9
  simple_animated_rating_bar: ^2.0.1
  scroll_time_picker: ^1.1.2
  scroll_datetime_picker: ^0.2.1
  kakao_flutter_sdk: ^1.9.7+3
  shared_preferences: ^2.5.3
  uni_links: ^0.5.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:

  uses-material-design: true

  assets:
  - assets/data/
  - assets/imgs/
  - assets/fonts/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
        - asset: assets/fonts/Pretendard-Light.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-SemiBold.ttf
        - asset: assets/fonts/Pretendard-Thin.ttf
