name: public_parking_info_fe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  kakao_map_plugin: ^0.3.6
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  dio: ^5.8.0+1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  flutter_dotenv: ^5.2.1
  riverpod: ^2.6.1
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  go_router: ^15.1.1
  sidebarx: ^0.17.1
  spider: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/data/
  - assets/imgs/
  - assets/fonts/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Black.ttf
        - asset: fonts/Pretendard-Bold.ttf
        - asset: fonts/Pretendard-ExtraBold.ttf
        - asset: fonts/Pretendard-ExtraLight.ttf
        - asset: fonts/Pretendard-Light.ttf
        - asset: fonts/Pretendard-Medium.ttf
        - asset: fonts/Pretendard-Regular.ttf
        - asset: fonts/Pretendard-SemiBold.ttf
        - asset: fonts/Pretendard-Thin.ttf